# This workflow will build a golang project

name: Go

on:
  push:
    branches: [ "release/*" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Go Coverage
      uses: gwatts/go-coverage-action@v1.2.0
      with:
        cover-pkg: ./...
        coverage-threshold: 0

    - name: GolangCI-Lint Action
      uses: matoous/golangci-lint-action@v1.23.3
      
